[package]
name = "near-pool"
version = "0.1.0"
authors = ["Near Inc <hello@nearprotocol.com>"]
edition = "2018"

[dependencies]
deepsize = { path = "../../deepsize" }
rand = "0.7"
borsh = "0.7.1"

near-crypto = { path = "../../core/crypto" }
near-primitives = { path = "../../core/primitives" }
